//389. Find the Difference
//Given two strings s and t which consist of only lowercase letters.
//String t is generated by random shuffling string s and then add one more letter at a random position.
//Find the letter that was added in t.
//
//Example:

//    Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//    e
//
//Explanation:
//'e' is the letter that was added.
#include <iostream>
#include "toolkit.h"

class Solution {
public:
    char findTheDifference(string s, string t) {
        int ans = 0, i, lens = s.length(), lent = t.length();
        for(i = 0; i < lens; i++)
            ans ^= (s[i] - 'a');
        for(i = 0; i < lent; i++)
            ans ^= (t[i] - 'a');
        return 'a' + ans;
    }
};

using namespace std;

int main() {
    Solution ss;
    string s = "abcd";
    string t = "abcde";
    char res = ss.findTheDifference(s, t);
    cout << res << endl;
    return 0;
}